### ISSUE TITLE
[BUG] 无法登陆  

### ISSUE THREAD

**Issue by kevin-zone** [csgowiki/message-channel#19]
![22U56NOX)14 D 2Z$HQD~$1](https://user-images.githubusercontent.com/84778568/149199223-a31d23b3-b575-4ac3-b525-93636cc6d539.png)

**Comment by hx-w** [comment]
删除go-cqhttp镜像后重新拉取最新的内容可以解决



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年01月13日 02:21 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [hx-w/message-channel] [BUG] 无法登陆   (Issue #19) |

**Comment by kevin-zone** [comment]
![L MCO1TT@~E)`QY8K%J7D@H](https://user-images.githubusercontent.com/84778568/149280922-7ed44601-264e-477b-9fd9-4b129bcfca75.png)

**Comment by hx-w** [comment]
需要确保mc-nomebot容器正常运行，可以看下mc-nonebot容器里的日志。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年01月13日 14:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [hx-w/message-channel] [BUG] 无法登陆   (Issue #19) |

**Comment by kevin-zone** [comment]
nonebot
 
![GL{R7Z 0(R9 )JQU{%3SIVS](https://user-images.githubusercontent.com/84778568/149286800-3e23df34-4c87-4d1b-bf70-7dcc132d5fc8.png)

**Comment by hx-w** [comment]
nonebot_config.py里的HOST和PORT不要手动更改，用默认的
